### ISSUE TITLE
Yum fails after first run

### ISSUE THREAD

**Issue by betelgeuse** [ANXS/postgresql#171] opened 2016-05-08 23:58 UTC
```
TASK [ANXS.postgresql : PostgreSQL | Add PostgreSQL repository] ****************
fatal: [10.198.13.52]: FAILED! => {"changed": true, "failed": true, "msg": "Virhe: Ei mitään tehtävää\n Warning: Due to potential bad behaviour with rhnplugin and certificates, used slower repoquery calls instead of Yum API.", "rc": 1, "results": ["Ladatut liitännäiset: product-id, rhnplugin, security, subscription-manager\nThis system is receiving updates from RHN Classic or RHN Satellite.\nAloitetaan asennusprosessi\nTutkitaan /var/tmp/yum-root-HhuVRi/pgdg-redhat95-9.5-2.noarch.rpm: pgdg-redhat95-9.5-2.noarch\n/var/tmp/yum-root-HhuVRi/pgdg-redhat95-9.5-2.noarch.rpm: ei päivitä asennettua pakettia\n"]}
    to retry, use: --limit @mirror.retry
```

The error is about not updating an installed package.

**Comment by jesselang** [comment] 2016-05-21 23:42
I haven't been able to reproduce this on CentOS 6 or 7. Perhaps this is something specific to RedHat?

**Comment by mjuenema** [comment] 2016-09-28 20:33
The problem is that the ```postgresql_yum_repository_url``` in ```defaults/main.yml``` has the release version hard-coded into it. Currently that's the ```2``` just before ```.noarch.rpm```.

Unfortunately the release version number of the ```pgdg...``` RPM is different for each PostgreSQL version and may be updated at any time. One would have to either maintain a mapping in ```defaults/main.yml``` or find a way to dynamically determine the current release to resolve this in an Ansible playbook.

**Comment by mjuenema** [comment] 2016-09-29 00:42
One could write a little helper script that extracts the correct name of the RPM package, e.g.
```
>>> f = urllib2.urlopen('https://yum.postgresql.org/9.0/redhat/rhel-6-x86_64')
>>> d = f.read()
>>> re.search('>(pgdg.+redhat.+rpm)', d).group(1)
'pgdg-redhat90-9.0-5.noarch.rpm'
```
Ansible could upload and execute such a script (providing the right arguments) and then read the registered output. Something similar to this (no syntax checked!!!)
```
- command: "python /path/to/script.py {{ postgresql_yum_repository_base_url }} {{ postgresql_version}} {{ ansible_os_family | lower }} {{ ansible_distribution_major_version }} {{ ansible_architecture }} {{ postgresql_pgdg_dists[ansible_distribution] }}
  register: pgdg_rpm_name
```

**Comment by gclough** [comment] 2018-03-23 12:12
@mjuenema , and @betelgeuse. Has this been fixed by the inclusion of this code in `defaults/main.yml`?  If so, can you close this issue?

```
postgresql_pgdg_releases:
  redhat: {
      9.1: 8,
      9.2: 9,
      9.3: 3,
      9.4: 3,
      9.5: 3,
      9.6: 3,
  }
  centos: {
      9.1: 7,
      9.2: 8,
      9.3: 3,
      9.4: 3,
      9.5: 3,
      9.6: 3,
  }
...
```

**Closed** 2018-03-28 11:20 UTC
