### ISSUE TITLE
Error while running init script

### ISSUE THREAD

**Issue by gs-rbarman** [ANXS/postgresql#140] opened 2016-01-14 10:28 UTC
...
==> app: Running provisioner: ansible...
    app: Running ansible-playbook...
PYTHONUNBUFFERED=1 ANSIBLE_FORCE_COLOR=true ANSIBLE_HOST_KEY_CHECKING=false ANSIBLE_SSH_ARGS='-o UserKnownHostsFile=/dev/null -o IdentitiesOnly=yes -o ForwardAgent=yes -o ControlMaster=auto -o ControlPersist=60s' ansible-playbook --connection=ssh --timeout=30 --limit='app' --inventory-file=/Users/neo/Documents/ABnap/abcd/.vagrant/provisioners/ansible/inventory --extra-vars={"user_env":{"SQS_TRANSCODER_QUEUE_NAME":"abnap-nithapu-transcoder"},"checkout_sources":false,"symlink_sources":true} -vvvv provisioning/vagrant.yml
Using /Users/neo/Documents/ABnap/abcd/ansible.cfg as config file
[DEPRECATION WARNING]: Instead of sudo/sudo_user, use become/become_user and 
make sure become_method is 'sudo' (default). This feature will be removed in a 
future release. Deprecation warnings can be disabled by setting 
deprecation_warnings=False in ansible.cfg.

ERROR! the role 'pjan.vandaele.postgresql' was not found in /Users/rajdeep/Documents/ABnap/abcd/provisioning/roles:/Users/rajdeep/Documents/ABnap/abcd/provisioning:./provisioning/galaxy:/Users/rajdeep/Documents/ABnap/abcd/provisioning/roles

The error appears to have been in '/Users/rajdeep/Documents/ABnap/abcd/provisioning/roles/db/meta/main.yml': line 3, column 7, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

  dependencies:
    - role: pjan.vandaele.postgresql
      ^ here

Ansible failed to complete successfully. Any error output should be
visible above. Please fix these errors and try again.

**Comment by farridav** [comment] 2016-01-15 17:54
What version of this role are you using ? There are no dependencies in this role, and the role that appears to be causing the problem is `db` which in guessing is your local role ?

**Comment by jlozadad** [comment] 2018-03-28 11:08
closing since this is not an issue

**Closed by jlozadad** 2018-03-28 11:09 UTC
